### ISSUE TITLE
Update Destroy Rotation

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Rotations#18]
# Currently the map rotations look like this
`<?xml version="1.0" encoding="UTF-8"?>
<rotation>
    <map>Railway</map>
    <map>Formorgar 2</map>
    <map>Unix</map>
    <map>Proelium1.5</map>
    <map>Dust Devils</map>
    <map>Sandstorm</map>
    <map>Ravanged</map>
    <map>Senex 1</map>
    <map>Senex 2</map>
    <map>Campi Erbosi Origins</map>
    <map>Sector Six</map>
    <map>Port Town 1</map>
    <map>Tallon Overworld</map>
</rotation>`
# It should look like....
```
<?xml version="1.0" encoding="UTF-8"?>
<rotation>
    <map>Ravanged</map>
    <map>Formorgar 2</map>
    <map>Unix</map>
    <map>Senex 1</map>
    <map>Proelium1.5</map>
    <map>Railway</map>
    <map>Dust Devils</map>
    <map>Fractal Descent</map>
    <map>Senex 2</map>
    <map>Sandstorm</map>
    <map>Port Town 1</map>
    <map>Sector Six</map>
    <map>Campi Erbosi Origins</map>
</rotation>
```

Thankyou :)

**Comment by master00ofdsiware** [comment]
It already looks like the bottom example, though.
